require 'active_support/json'
require 'active_support/core_ext/hash/deep_merge'
require 'active_support/core_ext/string/inflections'
require 'logger'
require 'optparse'
require 'yaml'

require 'modables_dsl/cli'
require 'modables_dsl/config'
require 'modables_dsl/dsl/arguments'
require 'modables_dsl/dsl/core'
require 'modables_dsl/generate'
require 'modables_dsl/message'
require 'modables_dsl/version'
